spring.application.name=user-services
spring.datasource.url=jdbc:postgresql://localhost:5433/nimbuscart_users
spring.datasource.username=nimbus
spring.datasource.password=nimbus123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=nimbusCartSuperSecretKeyChangeThisInRealProductionUseOnly123456
app.jwt.expiration-ms=86400000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/